#!/bin/bash

NODE=precursors_server_dev@$HOSTNAME
COOKIE=PreServDev

echo -e "\033[1;31mTo \033[0;30;41mkill the running server node\033[1;31m:\033[0;31m (while connected to the running node)\033[m"
echo
echo "    (precursors_server_dev@$HOSTNAME)3> q()."
echo "    (precursors_server_dev@$HOSTNAME)4>"
echo
echo -e "\033[31mThen, proceed with the following step to exit the shell.\033[m"
echo
echo -e "\033[1;32mTo exit your current shell (without killing the running node), first press \033[36mCtrl+G\033[32m; then:\033[m"
echo
echo "    User switch command"
echo "     --> q"
echo
echo -e "\033[33mConnecting to $NODE...\033[m"

erl -sname $USER -setcookie $COOKIE -remsh $NODE
